# 模型配置
model:
  name: "dinov2_vitb14"
  layer: 11
  vocab_path: "./models/aerial/c_centers-b.pt"
  device: "cuda"  # cuda or cpu
  warmup_iterations: 3

# 数据路径配置
data:
  database_dir: "/root/autodl-tmp/data/source_tiles/img"
  query_dir: "/root/autodl-tmp/data/target_drone_img"
  output_dir: "/root/autodl-tmp/data/descriptors"
  metadata_file: "/root/autodl-tmp/data/source_tiles/data.csv"

# 检索配置
retrieval:
  index_type: "faiss"
  similarity_metric: "cosine"
  top_k: 10
  use_gpu: true

# 预处理配置
preprocessing:
  target_size: 896
  patch_size: 14
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]